### ISSUE TITLE
Some files can break the module.

### ISSUE THREAD

**Issue by bogado** [mceachen/exiftool.rb#10]
The gem will choke if there's a field that has "Date" in it's key but is either not a Date or an invalid date.

Example : 
  "GPSDateTime": "0111:00:30 20:31:58Z" From Nexus S

**Comment by mceachen** [comment]
Thanks for the diff and the bug report. 

Is that from an image you have? Was it taken in 2011?

**Comment by mceachen** [comment]
Pushed v1.2.0 with a breaking test and your fix.
